### ISSUE TITLE
Admin error with 1.9.3

### ISSUE THREAD

**Issue by studio2f** [nexcess/magento-turpentine#1077]
Hello.

I'm using Turpentine 0.6.6. I've just upgraded to Magento 1.9.3. I didn't do the SUPEE-7405 patch, I did a complete upgrade from 1.9.2 to 1.9.3. I can't get past the admin login screen. I'm getting the following error. 

Any advice would be greatly appreciated. Thanks in advance.

```
a:5:{i:0;s:112:"Invalid method Nexcessnet_Turpentine_Model_Core_Session::validateFormKey(Array
(
    [0] => HMsmqBAn5dm2gPuV
)
)";i:1;s:1930:"#0 /home/XXXX/domains/XXXX/app/code/core/Mage/Admin/Model/Observer.php(73): Varien_Object->__call('validateFormKey', Array)
#1 /home/XXXX/domains/XXXX/app/code/core/Mage/Admin/Model/Observer.php(73): Nexcessnet_Turpentine_Model_Core_Session->validateFormKey('HMsmqBAn5dm2gPu...')
#2 /home/XXXX/domains/XXXX/app/code/core/Mage/Core/Model/App.php(1358): Mage_Admin_Model_Observer->actionPreDispatchAdmin(Object(Varien_Event_Observer))
#3 /home/XXXX/domains/XXXX/app/code/core/Mage/Core/Model/App.php(1337): Mage_Core_Model_App->_callObserverMethod(Object(Mage_Admin_Model_Observer), 'actionPreDispat...', Object(Varien_Event_Observer))
#4 /home/XXXX/domains/XXXX/app/Mage.php(448): Mage_Core_Model_App->dispatchEvent('controller_acti...', Array)
#5 /home/XXXX/domains/XXXX/app/code/core/Mage/Core/Controller/Varien/Action.php(527): Mage::dispatchEvent('controller_acti...', Array)
#6 /home/XXXX/domains/XXXX/app/code/core/Mage/Adminhtml/Controller/Action.php(160): Mage_Core_Controller_Varien_Action->preDispatch()
#7 /home/XXXX/domains/XXXX/app/code/core/Mage/Core/Controller/Varien/Action.php(407): Mage_Adminhtml_Controller_Action->preDispatch()
#8 /home/XXXX/domains/XXXX/app/code/core/Mage/Core/Controller/Varien/Router/Standard.php(254): Mage_Core_Controller_Varien_Action->dispatch('index')
#9 /home/XXXX/domains/XXXX/app/code/core/Mage/Core/Controller/Varien/Front.php(172): Mage_Core_Controller_Varien_Router_Standard->match(Object(Mage_Core_Controller_Request_Http))
#10 /home/XXXX/domains/XXXX/app/code/core/Mage/Core/Model/App.php(365): Mage_Core_Controller_Varien_Front->dispatch()
#11 /home/XXXX/domains/XXXX/app/Mage.php(684): Mage_Core_Model_App->run(Array)
#12 /home/XXXX/domains/XXXX/index.php(83): Mage::run('', 'store')
#13 {main}";s:3:"url";s:6:"/admin";s:11:"script_name";s:10:"/index.php";s:4:"skin";s:5:"admin";}

```

**Comment by miguelbalparda** [comment]
I don't think this issue has nothing to do with the new Magento release. Can you try upgrading Turpentine to the latest version? If you check the said class, there is no method called validateFormKey.

**Comment by studio2f** [comment]
Will do

**Comment by miguelbalparda** [comment]
I would also try to flush cache, it seems your Magento is looking for a method in the wrong class for some reason. I'm downloading 1.9.2.3 to see if I can replicate your issue.

**Comment by miguelbalparda** [comment]
I just installed Magento 1.9.2.3 and the latest Turpentine release and it seems to be working.

![t1923](https://cloud.githubusercontent.com/assets/3997682/12463332/b3b4c2aa-bfa1-11e5-837c-123dfdfa0acd.png)

**Comment by aricwatson** [comment]
I patched our [test server](turpentine-master.devsupport.nexcess.net) w/out any problems at all.

**Comment by studio2f** [comment]
This is getting a little beyond my skillset...I'm embraced to say I'm still having trouble.  I've reverted back to 1.9.2 and applies just the patch and not the full upgrade. I've also updated Turpentine to 0.6.8. I'm still stuck.

validateFormKey seems to have been added in the SURPEE-7405 patch. Lines 66-75 of app/code/core/Mage/Core/Model/Session.php adds the all new new function validateFormKey

**Comment by thaiphan** [comment]
@studio2f Have you tried clearing your cache? It looks like Turpentine have swapped out their local override of Mage_Core_Model_Session with a rewrite. You will need to clear your config cache for the change to start working.

**Comment by studio2f** [comment]
First off- thanks for all the help. Cache cleaning, reindexing and more full installs and the error is gone but I still can't get into the Admin. Now the Admin is returning "Invalid Form Key. Please refresh the page."

![login](https://dl.dropboxusercontent.com/u/8230194/Screen%20Shot%202016-01-20%20at%207.54.27%20PM.png)

It appears an admin cookie is not getting set. There's no problem on the frontend-- users can add to cart, log into their account and checkout. Form keys and cookies are working fine on the frontend. It's just the admin. Despite how it looks, I'm running a fairly stock 1.9.2 with no admin modifications and fronted theme that is almost 99% madison island.

**Comment by studio2f** [comment]
So appears to be form key changes to the admin:

http://magento.stackexchange.com/questions/98220/security-patch-supee-7405-possible-problems/98236#98236

**Comment by mvenghaus** [comment]
It is a complete file replacement .. so you have to add the functions in
app/code/local/Mage/Core/Model/Session.php

...

/**
	 * Creates new Form key
	 */
	public function renewFormKey()
	{
		$this->setData('_form_key', Mage::helper('core')->getRandomString(16));
	}

	/**
	 * Validates Form key
	 *
	 * @param string|null $formKey
	 * @return bool
	 */
	public function validateFormKey($formKey)
	{
		return true;
		return ($formKey === $this->getFormKey());
	}

**Comment by miguelbalparda** [comment]
@mvenghaus we removed app/code/local/Mage/Core/Model/Session.php a while ago, you should not have that file there (at least not from Turpentine). @studio2f if you have that file from an older version, please remove it, flush cache and try again.

**Comment by larascasse** [comment]
@miguelbalparda , works for me, thank you

**Comment by miguelbalparda** [comment]
@larascasse you were having this same issue?

**Comment by studio2f** [comment]
I did have that file. I've removed it, cleared the cache and cookies but I'm still getting the "Invalid Form Key" on the admin login :(

**Comment by miguelbalparda** [comment]
Weird, at this point I'm not entirely sure it has something to do with Turpentine. Do you still have this error if you remove/disable the extensions?

**Comment by studio2f** [comment]
Alright, If I bypass varnish on my staging server, I can log in without the form key problem. I'm not sure how to diagnose what the varnish problem is. I'm check with my host to make sure I don't have any config problems.

**Comment by miguelbalparda** [comment]
See https://github.com/nexcess/magento-turpentine/wiki/Configuration#general-options for more info.

**Comment by studio2f** [comment]
Thanks @miguelbalparda for your help. I'll keep investigating.

**Comment by obi12341** [comment]
removing app/code/local/Mage/Core/Model/Session.php worked for us! Thank you :+1:

**Comment by inluxc** [comment]
Same here, i dont have the file app/code/local/Mage/Core/Model/Session.php and i get the error.

**Comment by aricwatson** [comment]
@inluxc did you clear your caches - all of them including sessions?

**Comment by phpdave11** [comment]
I had the same problem after upgrading to Magento 1.9.2.3.  Removing `app/code/local/Mage/Core/Model/Session.php` fixed the problem.

**Comment by muhupower** [comment]
@studio2f did you solve this issue? I am also getting the same problem after login into admin after ftp upgrade to SUPEE-7405.... I am not using a turpentine with my install... So it might be unrelated to it..

**Comment by Nuranto** [comment]
I'm also getting the error after applied patch 7405.

**Comment by studio2f** [comment]
I have not solved it. If I bypass varnish by visiting site.com:8080/admin there are no form key problems.

**Comment by aricwatson** [comment]
Not sure, and haven't been able to replicate it... Any requests to the admin should be getting piped by Varnish anyways, so I'm not sure how this is happening. Can you look at the source being generated for the form to make sure it's not trying to do ESI includes or something like that?

**Comment by ccl28** [comment]
I am using version 0.6.1. Is it safe for me to remove the local Session.php?

**Comment by miguelbalparda** [comment]
@ccl28 no, we were still using that file. I do suggest you to update Turpentine to the latest version.

**Comment by kanduvisla** [comment]
I have the same questions as @ccl28 : from what version is it safe to remove the file in question?

**Comment by miguelbalparda** [comment]
We removed the Session.php file in release-0.6.3 (https://github.com/nexcess/magento-turpentine/blob/master/CHANGELOG.md#release-063)

**Comment by hellraiser2005** [comment]
Upgraded magento to 1.9.2.4 and turpentine to version 0.6.8 and removed the old session file and i still have the invalid formkey error.

**Comment by aricwatson** [comment]
@hellraiser2005 which error are you seeing, and where? 

Did you try clearing all caches?

**Comment by hellraiser2005** [comment]
@aricwatson yes the var/cache map is empty, restarted varnish. I see the error on the backend login screen. After hitting user and pass. Same as the screenshot of studio2f. We have magento in git repo, so i reverted back to the working version. But still the error is there, that i dont understand.

**Comment by hellraiser2005** [comment]
Yesterday i deleted all code and did a fresh install of 1.9.2.4 without any custom modules. And still the same problem. Then i reverted back to the working version before 1.9.2.4 and modules. It works and i can login. So if its not the code then what configuration issues are there?

I use nginx, memcached for sessions, redis for backend cache and varnish. Hope that somebody can help me.

**Comment by tttungs** [comment]
@hellraiser2005  could be cache issue, let try clear cache session in memcache and cache backend in redis then restart varnish and browser. Should work after that. hope it help

**Comment by hellraiser2005** [comment]
@tttungs Thank you for the comment. But unfortunally still the same error. Everything is cleared.
What I see is that the session key changes in the post process.

The log is from app/code/core/Mage/Core/Model/Session.php in the function getFormKey after the if (!$this->getData('_form_key')) {

2016-03-18T09:29:40+00:00 DEBUG (7): renewFormKey
2016-03-18T09:29:40+00:00 DEBUG (7): xx2zmYEAbGk3Swx3
2016-03-18T09:29:55+00:00 DEBUG (7): renewFormKey
2016-03-18T09:29:55+00:00 DEBUG (7): 9wnl7XG8xgvs3CoN

This happens only in the new code and not the old working code. Cant find the problem. Its frustrating to not finding the solution.

**Comment by aricwatson** [comment]
Sorry if you already tried this and I missed it - did you try turning *off* all the non-varnish cache types under Cache Management? Do you have any other caching extensions?

**Comment by hellraiser2005** [comment]
@aricwatson I run the following statement "update `core_cache_option` set `value` = 0". Then cleared everything and still the same problem.

**Comment by ADDISON74** [comment]
I am getting the same issue after installing Magento 1.9.2.4 from scratch i cannot login into Backend because an "Invalid Form Key". 

Here is my scenario:
1) Clear your browser cache and cookies.
2) Clear all files in Magento var/cache and var/session folders contents.
3) Connect into your Backend. Check if you can save the changes for example in System -> Configuration. It should work without any issues.

Now the "nice" part:
4) Go to Frontend and visit My Account section.
5) Go back in Backend and try changing something and save. You will be redirected to Dashboard (my case). This is acting like having the backend cached.

If you Logout and try again login you will get the error message. I suspect there is a conflict between cookies/formkeys Frontend - Backend.

The only way to get rid off this is clearing you browser cache, clear cookies (I am using EditThisCookie extension in Chrome for easy checking or deleting). Then on server clearing Magento cache and session and restarting Varnish service.

This is not good at all. Today we got this report from one of our customer who struggled all the morning to save changes in products in backend without any luck. I disabled Varnish for him, it is working correctly and expect someone finding a solution for this stupid issue related to formkeys. All trouble comes from frontend/backend formkey mix related to Admin.

**Comment by aricwatson** [comment]
FWIW, I just tested this and could *not* replicate it (if I'm understanding the problem) - however I was using the master branch, will test with devel

**Comment by aricwatson** [comment]
Just a note on this - we encountered a very similar problem with a client that was *not* using varnish or turpentine. In this case clearing memcache (which they used for sessions) solved the invalid formkey problem.

**Comment by flancer64** [comment]
I have the same behavior in 1.9.2.4. Deleting the admin session cookie (named "adminhtml") is solved this problem. This behavior is not stable - one only browser was affected and I cannot repeat this situation in other browsers. But login was succeed after I have removed the "adminhtml" session cookie.

**Comment by beckindesigns** [comment]
Here is what worked for me and I don't see this answer anywhere.

In my case it was a turpentine setting. I used the backdoor to get into the admin area by going to the downloader page (yoursite.com/downloader) and logging in. After that, I changed **_System > Configurations > Turpentine > Varnish Options > General Options > Use VCL fix_** to "disabled".

"When Enable is selected, a VCL fix will be used to prevent formKey issues. If Disable is selected, an observer will be used."

It appears the observer did the trick. Also, I am not using an override of the `app/code/local/Mage/Core/Model/Session.php` file.

**Comment by Fabryz** [comment]
Hello, I'm new of Magento: I have just made a clean install of Magento CE 1.9.2.4 (magento-1.9.2.4-2016-02-23-06-04-07.tar.gz), set "var/session" and "var/cache" folders permissions to 777, cleared them up from any file inside, but I'm unable to login as an admin because of that "Invalid Form Key. Please refresh the page." error.
Deleting cookies doesn't change anyhing, tested in FF/Chrome, even in the incognito mode

Any help?

**Comment by ADDISON74** [comment]
This is not a Turpentine issue it is related to Magento sessions. If you do a search by Google you will get more information about this. Normally if you delete /var/session/ content it should work just fine. If not the new security features included in latest version of Magento create a little trouble. Just use Google for: magento invalid form key. Some guys gave clues what files to edit in order to make it working again. Deleting session content should resolve this issue in 90% of the cases.

**Comment by Fabryz** [comment]
@ADDISON74 Yep sorry, hoped to jump on the same wagon. 
I have already googled around and nothing suggested have worked.
I had to put my sessions on the DB to be able to login successfully

**Comment by mihaifaget** [comment]
maybe no write permission to var folder ?

**Comment by rluders** [comment]
I'm having the same problem. I just change my domain and I'm getting this error when I try to login into the admin panel. So, I did clear the `var/session` and also `var/cache' and the error still there. I'm not able to find the `Session.php` file inside the path mentioned. I'm using the last 1.9 magento. How do I fix it? Oh, another tip... It's not my browser, I also change to anon tab and try to access it from other computer and browser.

**Comment by ADDISON74** [comment]
This is an old issue but I would like to add a few things:

- it is not related to Turpentine extension
- it is a cookie issue
- only Google Chrome is affected, use Firefox instead
- do not use IP address in your Base URL. set up Magento for using http://www.mydomain.com
- magento.stackexchange.com has a few solutions if you search for "Invalid form Key"

**Comment by Nuranto** [comment]
Warning, I think you should rename the title for Admin error with 1.9.2.3
Now that 1.9.3 is released, it is confusing.

**Comment by hellraiser2005** [comment]
I had an issue in my vcl.
sub vcl_fetch {
    if (beresp.http.Set-Cookie) {
        set beresp.http.X-Varnish-Set-Cookie = beresp.http.Set-Cookie;
        unset beresp.http.Set-Cookie;
    }

changed it to

sub vcl_fetch {
    if (beresp.http.Set-Cookie) {
        set beresp.http.X-Varnish-Set-Cookie = beresp.http.Set-Cookie;
    }

**Comment by vladfr** [comment]
@hellraiser2005 not sure why was that line there, but it was! Removed it, and now it works. Thanks!

**Comment by hellraiser2005** [comment]
@vladfr I think now we see some issues, mixed carts of other customers. Login logout problems.
That was totally not the fix, arg. I hate vcl's. And also that i dont have the correct knowelge for it.

**Comment by vladfr** [comment]
Yeah, keeping the original cookies in the request ends up bypassing the
cache. This is not the fix :( I don't really have another one atm.
