### ISSUE TITLE
Missing blocks and product in categories in master branch

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#1086]
I just installed the master branch after 8 months of using only devel branch (the latest version has a syntax issue and cannot be used so I gave it a try to master version). Configuration is made as usual. Once I enable Varnish ESI Blocks, right side blocks are disappearing and there are no products in a category page. Layering Navigation is showing results, I can filter with results, but page content is always empty. Disabling Varnish ESI Blocks everything is going back to normal.

In this moment I am in a cross point. Master version has issues, Devel version has issue. Please fix devel version for syntax issue and I will never go back to master branch. I don't know what is happening but I have to find archives from December to make this working.

**Comment by ADDISON74** [comment]
This issue is not appearing in a devel version from December installed a few moments ago. What a shame both branches are having issues in the same time.

**Comment by miguelbalparda** [comment]
Definitely no shame. There are quite a few developers contributing here and it is pretty normal for a bug to be introduced. This is how any OSS project works. Please be respectful with the work of others and if you think "nothing works" feel free to submit a PR to fix it.

**Comment by ADDISON74** [comment]
Miguel it is clear to me you are not a native English speaker. "Shame" in this case is associated with sorry or regret.

**Comment by ADDISON74** [comment]
This is not a matter of respect. Word "shame" could have unknown issues for some people. Please investigate this issue because is your master branch and find a way to make it working. In this moment none of your versions are working properly.

**Comment by ADDISON74** [comment]
I managed to get working the devel branch (see #1085 ). As I mentioned in my initial report it was a syntax error in that case. Working with devel version I confirm this issue appears in that version too. Both branches are affected. I used a master version from October and works as expected, no issues. As a suggestion revert master branch to previous versions for a while.

**Comment by 2des** [comment]
Hello,

i made all the modification (#1085), when i hit Apply Varnish config in backend admin, i get a blank page, both admin and frontend. I need to restart varnish (systemctl restart varnish.service) to get the page.

Thank you for helping.

**Comment by 2des** [comment]
Maybe this is becausei use redis cache (http://redis.io/) ?

**Comment by ADDISON74** [comment]
It is not related to Redis, I did not install it but having the same issue. It is related to Varnish/Turpentine configuration. I tried different parameters for starting Varnish service but without any luck. 

```php
ExecStart=/usr/sbin/varnishd \
	-P /var/run/varnish.pid \
	-f $VARNISH_VCL_CONF \
	-a ${VARNISH_LISTEN_ADDRESS}:${VARNISH_LISTEN_PORT} \
	-T ${VARNISH_ADMIN_LISTEN_ADDRESS}:${VARNISH_ADMIN_LISTEN_PORT} \
	-t $VARNISH_TTL \
	-u $VARNISH_USER \
	-g $VARNISH_GROUP \
	-S $VARNISH_SECRET_FILE \
        -p feature=+esi_ignore_other_elements \
        -p feature=+esi_disable_xml_check \
        -p vcc_allow_inline_c=on \
        -p cli_buffer=16384 \
        -p thread_pool_add_delay=2 \
        -p thread_pools=4 \
        -p thread_pool_min=200 \
        -p thread_pool_max=4000 \
        -s malloc,2G
```

Try disabling in Magento backend [Varnish ESI Blocks] only and see what's happening. In my case products appears in categories, also side blocks.

What Linux flavor are you using? CentOS 7 with Varnish 4?

**Comment by 2des** [comment]
Hello,

i am using centos7 and varnish 4.
The caching:
Varnish Pages
Varnish ESI Blocks ware and are disabled.

I use varnish setting:
DAEMON_OPTS="-p vcc_allow_inline_c=on -p feature=+esi_ignore_other_elements -p cli_buffer=16384"

**Comment by ADDISON74** [comment]
Debian/Ubuntu versions are not affected, after a first install from scratch a half an hour ago. But there is a problem with Varnish 4 on CentOS 7/systemd. There are many issues reported here all of them in CentOS. For the moment I am trying finding a solution.

**Comment by 2des** [comment]
Hello ADDISON74,

please write it down if you find the solution. i am wary interested to get this varnish cache to work.

Best regards

**Comment by ADDISON74** [comment]
I guess everybody is happy with Turpentine because they are using other OS versions than CentOS. I set up again from scratch CentOS 7/Varnish/Magento CE1.9.2.2/Turpentine 0.6.8 and devel. As you can see if [Varnish ESI Blocks] is enable the whole page content, footer and side blocks are disappearing. I really don't have any idea for the moment from where is this coming. My suggestion to you is if you want using Varnish in Magento switch to Debian 7.9 x64. It will take some time to solve this annoying issue.

![missing_products](https://cloud.githubusercontent.com/assets/8360474/12704554/9a7bdbd4-c866-11e5-8ee4-fbafb2f3d35d.jpg)

**Comment by aricwatson** [comment]
The devel branch issue is fixed in https://github.com/nexcess/magento-turpentine/pull/1087.

Rest assured CentOS is important to us - nearly all our servers run CentOS.

**Comment by ADDISON74** [comment]
This is not a Turpentine issue in my opinion. it is related to Varnish 4.0 repo build in my opinion. Why everything goes perfect in Debian 7/8 and Ubuntu but not in CentOS 7? Something bad is happening look above all ESI blocks are missing. If Varnish ESI Blocks is disabled in backend they are back. I tried a lot of parameters to start Varnish service without any luck. I can apply configuration, Varnish/Trupentine report no error, but result in frontend is not the one I expected. There are no errors in logs (Turpentine, Magento, Apache, ...) everything works as normal.

I read some articles about issues in 4.0.3. PageCache from Phoenix Media skipped all Varnish 4.0 versions, but warning people to switch to 4.1. I guess it was a RedHat flavour.

PS - Normally I am a Debian geek, but I got a good task which includes cPanel. This panel is not working in Debian, so I had to install CentOS. With this occasion, I set up the whole thing for Magento with Varnish/Turpentine. I get this issue with missing content. I tried Varnish 4.1 but Turpentine is not ready for it. For the moment I suggested to skip Varnish/Turpentine if they want CentOS 7. If you are interested I can post all steps to get Varnish working, but they are the same like in Debian, except systemd and varnish.params file. I can run fine Varnish 4 with Turpentine configuration but no blocks.

**Comment by ADDISON74** [comment]
@2des: I found the solution for getting this working in CentOS 7 x64, Magento 1.9.2.3, Turpentine latest Devel branch and Varnish-4.0.3 revision b8c4a34. All trouble comes from Varnish restart/reload options.

1) First copy this file <strong>/lib/systemd/system/varnish.service</strong> to <strong>/etc/systemd/system/varnish.service</strong>.

2) Edit <strong>/etc/systemd/system/varnish.service</strong> and add a <strong>#</strong> for comment before lines <strong>ExecStartPre</strong> (responsibile for Restart) and <strong>ExecReload</strong> (I did not evaluate this one for the moment but I preferred to comment it). Here is the file content at the final:

```php
Type=forking
PIDFile=/var/run/varnish.pid
PrivateTmp=true
#ExecStartPre=/usr/sbin/varnishd -C -f $VARNISH_VCL_CONF
ExecStart=/usr/sbin/varnishd \
        -P /var/run/varnish.pid \
        -f $VARNISH_VCL_CONF \
        -a ${VARNISH_LISTEN_ADDRESS}:${VARNISH_LISTEN_PORT} \
        -T ${VARNISH_ADMIN_LISTEN_ADDRESS}:${VARNISH_ADMIN_LISTEN_PORT} \
        -t $VARNISH_TTL \
        -u $VARNISH_USER \
        -g $VARNISH_GROUP \
        -S $VARNISH_SECRET_FILE \
        -s $VARNISH_STORAGE \
        $DAEMON_OPTS

#ExecReload=/usr/sbin/varnish_reload_vcl

```

3) Execute as root <strong>systemctl daemon-reaload</strong> (you just modified a systemd configuration file).

4) Now we will focus on Varnish start parameters. Edit file <strong>/etc/varnish/varnish.params</strong>. 

- VARNISH_LISTEN_PORT=80
- VARNISH_STORAGE="malloc,1G" <--- by default Varnish is caching in a file
- DAEMON_OPTS="-p vcc_allow_inline_c=on -p feature=+esi_disable_xml_check,+esi_ignore_other_elements -p cli_buffer=16384"

Here is the file content in my case, I backup some lines with # do not edit them directly.

```php
# Varnish environment configuration description. This was derived from
# the old style sysconfig/defaults settings

# Set this to 1 to make systemd reload try to switch vcl without restart.
RELOAD_VCL=1

# Main configuration file. You probably want to change it.
VARNISH_VCL_CONF=/etc/varnish/default.vcl

# Default address and port to bind to. Blank address means all IPv4
# and IPv6 interfaces, otherwise specify a host name, an IPv4 dotted
# quad, or an IPv6 address in brackets.
# VARNISH_LISTEN_ADDRESS=192.168.1.5
VARNISH_LISTEN_PORT=80

# Admin interface listen address and port
VARNISH_ADMIN_LISTEN_ADDRESS=127.0.0.1
VARNISH_ADMIN_LISTEN_PORT=6082

# Shared secret file for admin interface
VARNISH_SECRET_FILE=/etc/varnish/secret

# Backend storage specification, see Storage Types in the varnishd(5)
# man page for details.
#VARNISH_STORAGE="file,/var/lib/varnish/varnish_storage.bin,1G"
VARNISH_STORAGE="malloc,1G"

# Default TTL used when the backend does not specify one
VARNISH_TTL=120

# User and group for the varnishd worker processes
VARNISH_USER=varnish
VARNISH_GROUP=varnish

# Other options, see the man page varnishd(1)
#DAEMON_OPTS="-p thread_pool_min=5 -p thread_pool_max=500 -p thread_pool_timeout=300"
#DAEMON_OPTS="-p vcc_allow_inline_c=on -p feature=+esi_disable_xml_check,+esi_ignore_other_elements -p shm_reclen=4084 -p cli_buffer=16384"
DAEMON_OPTS="-p vcc_allow_inline_c=on -p feature=+esi_disable_xml_check,+esi_ignore_other_elements -p cli_buffer=16384"
```

5) Start/Restart Varnish service for checking if it is working <strong>systemctl start|restart varnish.service</strong>. It should start/restart without any issues. You can use <strong>varnishadm </strong>command for getting all parameter values (param.show -l or just param.show). Look for the following parameters: feature, cli_buffer, vcl_allow_inline_c and check if they have values.

6) Backup <strong>/etc/varnish/default.vcl</strong> to <strong>/etc/varnish/default.vcl.original</strong>. You will use this file always when you Turpentine VCL is creating trouble. It is the original VCL and works all the time.

7) I presume you installed Turpentine already and make the proper changes in its configuration. Go to Magento backend in Cache Management and click on <strong>[Save Varnish Configuration]</strong> button. You will get Turpentine VCL in your Magento folder <strong>/var/default.vcl</strong>. 

8) Remove file <strong>/etc/varnish/default.vcl</strong> then create as root a symbolic link from <strong>/home/YOUR_USER_NAME/public_html/var/default.vcl</strong> to <strong>/etc/varnish/default.vcl</strong> (ln -s). Every time you change/save/apply Turpentine configuration Varnish will reload the new configuration content.

That's it for Varnish part.

**Comment by ADDISON74** [comment]
... <strong>but ESI ISSUE IS STILL THERE!</strong>

Your website will load fast now but you won't take the benefits of ESI policies. In my case I had to disable [Varnish ESI Blocks] in Cache Management for getting some blocks visible (no products in categories, no side blocks). But with it disable I was not able to do compare for example. Just clicking on the button and nothing happening. When I visited any next page all messages are bonded one by one informing you just add a product for comparison. In my opinion it is not a Turpentine issue, it is related to Varnish version. Unfortunately I did not check it with Varnish 4.1.

<strong>IMPORTANT</strong>: Do not use/upgrade in production Varnish 4.0.3 on CentOS 7 x64 without doing intensive test!!!

**Comment by 2des** [comment]
Hello @ADDISON74

Thank you for investing your time to resolving this issue.
I will go for centos 6 and varnish 3.

Thank you,
Best regards.

**Comment by ADDISON74** [comment]
@2des: I installed a few moments ago Varnish-4.1.1 revision 66bb824. Instructions are here: https://www.varnish-cache.org/installation/redhat. Varnish start params are here:

```php
DAEMON_OPTS="-p cli_buffer=16384 -p feature=+esi_disable_xml_check,+esi_ignore_other_elements -p vsl_reclen=4084 -p vcc_allow_inline_c=on"
```

ESI policies are working as expected, no missing blocks or products in categories. In Cache Management everything is enabled. Turpentine saves the configuration and applies it without any issues. Still testing ...

<strong>There is one conclusion</strong>, in CentOS 7 skip Varnish 4.0! Turpentine owners should focus on making this extension working for Varnish 4.1. I will close this issue and post a new one with the conclusion and a warning.

**Comment by ADDISON74** [comment]
In Varnish 4.1.1 the first issue I saw was related to Age header set to 0. I hope Turpentine developers will find a solution for it asap. More details in here: #1089.

**Comment by farazhkhan** [comment]
@aricwatson @miguelbalparda @ADDISON74 

Can you please make cautionary note here at https://github.com/nexcess/magento-turpentine/wiki/Installation for people who are going to install it for CentOS 7.x because like me all CentOS users are facing issues with CentOS 7+Varnish. Had I ever known this I would have not installed it on CentOS 7.x in first place.

**Comment by ADDISON74** [comment]
My report is dated January 2016 it is more than a year behind. At that time there were a lot of developers having trouble with Varnish 4.0. I stopped using Varnish 4.0 in CentOS going back to version 3.0. Of course I was using the official repository. I tried many tricks inside the code getting a custom compiled version without any luck. If now Varnish 4.0 works as expected I am glad they fixed the issues.
