### ISSUE TITLE
Although Turpentine is installed and configured correctly, Varnish wouldn't work with Magento

### ISSUE THREAD

**Issue by linhvh** [nexcess/magento-turpentine#1165]
Hi, i have done exactly the steps for installing and configuring Turpentine to make Varnish works with Magento. 
I use host CentOS 6 on Amazon EC2. My webserver is NGINX. I have installed LEMP stack, Magento, Varnish and Turpentine. Below is the information of the versions i installed:
- NGINX version: 1.0.15
- Magento CE 1.9.1.0 with sample data
- Varnish version: 3.0.7
- Turpentine version: 0.6.9

The NGINX webserver is running on port 8080, and Varnish is running on port 80 to make it works together.
When the Turpentine is not installed yet, I check the HTTP header from my Magento site and receive the response header below:
![1](https://cloud.githubusercontent.com/assets/13230680/14848298/36a28476-0c97-11e6-9fab-a999200713f2.jpg)
When the Turpentine is installed and configured correctly from the instructions (after configuring, I press the Apply Varnish Config button), I check the HTTP header again and receive the response header below:
![2](https://cloud.githubusercontent.com/assets/13230680/14848438/db8c640c-0c97-11e6-93fa-0b64144f4931.jpg)
From this response header it seems that Varnish won't work with Magento, so why couldn't it work and how to fix it? Please help me, i need to fix this problem this week. If you need any information about my server, please tell me. Thank you so much!!!

**Comment by aricwatson** [comment]
Remember that the first request gets passed through to magento (if you're using the "VCL fix") - so you may always be getting this 'first request' behavior if you're testing from the command line and looking at headers. Try testing from the browser and reload the page.

**Comment by linhvh** [comment]
I try testing from the browser (Chrome) and reload the page but it seems that nothing has change. 
Here is the result:
![3](https://cloud.githubusercontent.com/assets/13230680/14853980/f3e4a0a8-0cb7-11e6-9f54-db9863350b88.jpg)

**Comment by aricwatson** [comment]
Yeah, it's acting like the Turpentine-generated VCL has not been applied. No ESI blocks are being inserted, and the `varnish_bypass` cookie is being ignored. There were no errors when you applied the VCL from the *cache management* screen? You're sure Varnish is running on port 80?

**Comment by linhvh** [comment]
Yeah, my Varnish is running on port 80, you can see the programs on my system and its listening port here:
![4](https://cloud.githubusercontent.com/assets/13230680/14856610/01da646c-0cc3-11e6-9df9-7ab5d52f3f6c.jpg)
At the beginning, when I applied the VCL from Cache Management, i got this error:
![5](https://cloud.githubusercontent.com/assets/13230680/14856939/6ba84192-0cc4-11e6-92f2-8e91540e480b.jpg)
I fixed this error by using this command from SSH client:
`sudo setsebool -P httpd_can_network_connect 1`
And then I retried to apply the VCL from Cache Management, it was successfully applied:
![6](https://cloud.githubusercontent.com/assets/13230680/14857095/2103fdd8-0cc5-11e6-9fc8-58399abf499f.jpg)
So what's the problem here? Please help me as soon as possible, thank you so much!

**Comment by aricwatson** [comment]
Please try disabling all the cache types *except* for the last two ("Varnish Pages" and "Varnish ESI Blocks") - in other words, the reverse of your current setup. You can re-enable other cache types later after testing - but those two Varnish cache types *must* be enabled.

**Comment by linhvh** [comment]
I tried it, but nothing has change... i don't know whether it is related to browser cache or not

**Comment by aricwatson** [comment]
When I check the IP in your screenshots I still don't see any ESI blocks, nor does it respect the varnish_bypass cookie - so something is still wrong somewhere. The only thing I can think is to restart varnish, re-apply the VCL from turpentine and clear all the caches then test again.

**Comment by aricwatson** [comment]
Closing for lack of feedback
