### ISSUE TITLE
AJAX login clears session

### ISSUE THREAD

**Issue by iamlolz** [nexcess/magento-turpentine#1203]
Hi turpentine team, thank you for all the hard work you've put into this software. It's been a pleasure to use.

The ajax login functionality in our onestep checkout page([this one](http://www.magestore.com/magento-one-step-checkout-extension.html/)) isn't working. Instead of logging in and reloading the checkout page it's remaining logged out and clearing the cart, which then sends me to the "You have nothing in your cart" page. The normal login works fine.

I'm using Turpentine 0.6.9 with Magento CE 1.9.2.4 and Varnish 4.1.2. Running on nginx and centos 7.
  
I have the login block excluded in local.xml like so:  
```
<reference name="login-popup">
    <action method="setEsiOptions">
        <params>
            <access>private</access>
            <ttl>0</ttl>
        </params>
    </action>
</reference>
```  
  
It sends a POST request to `/onestepcheckout/ajax/login/` and I have this blacklisted, as well as all of the checkout pages. Here are the headers for that request:
  
**Request Headers:**  
```
POST /onestepcheckout/ajax/login/ HTTP/1.1
Host: [example]
Connection: keep-alive
Content-Length: 74
Origin: http://[example]
User-Agent: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.84 Safari/537.36
Content-type: application/x-www-form-urlencoded; charset=UTF-8
Accept: text/javascript, text/html, application/xml, text/xml, */*
X-Prototype-Version: 1.7
X-Requested-With: XMLHttpRequest
Referer: http://[example]/onestepcheckout/index/
Accept-Encoding: gzip, deflate
Accept-Language: en-US,en;q=0.8
Cookie: SLIBeacon_257098331=MELWQWNWR1465958683589EXFANWIKF; SLI2_257098331=MELWQWNWR1465958683589EXFANWIKF.1465958683589.3.0; adminhtml=fdu4331tlh5ar4a4ooq42h2ob3; frontend=gl297a6skj587a24b940u33fv1
```  
  
**Response Headers:**  
```
HTTP/1.1 200 OK
Server: nginx
Date: Thu, 16 Jun 2016 06:56:53 GMT
Content-Type: text/html; charset=UTF-8
X-Frame-Options: SAMEORIGIN
Content-Encoding: gzip
X-Varnish-Host: 52.73.143.44
X-Varnish-URL: /onestepcheckout/ajax/login/
X-Varnish-Set-Cookie: frontend=gl297a6skj587a24b940u33fv1; expires=Fri, 17-Jun-2016 06:56:53 GMT; path=/; domain=[example]; httponly
Vary: Accept-Encoding
X-Varnish: 229812
Age: 0
Via: 1.1 varnish-v4
X-Varnish-Hits: 0
X-Varnish-Esi-Method: 
X-Varnish-Esi-Access: 
X-Varnish-Currency: 
X-Varnish-Store: 
Accept-Ranges: bytes
Content-Length: 36
Connection: keep-alive
Request Headers
```
  
Here is my turpentine.log starting immediately before I login:  
```
2016-06-16T06:44:53+00:00 DEBUG (7): TURPENTINE: Cleared ESI cache for client (5l408p4ttf1msf64sqbahhc3u4) on event: customer_login
2016-06-16T06:44:53+00:00 DEBUG (7): TURPENTINE: Cleared ESI cache for client (5l408p4ttf1msf64sqbahhc3u4) on event: sales_quote_save_after
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: root
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: head
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: js_cookies
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: optional_zip_countries
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: google_analytics
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: sli_search_top_js
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: head.calendar
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: after_body_start
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: turpentine_notices
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: top_scripts
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: header
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: sliSearch
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: global_notices
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: global_messages
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: breadcrumbs
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: content
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: content_top
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: emailcatcher
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: checkout.cart
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: messages
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: footer
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: before_body_end
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: global_cookie_notice
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: sli_search_bottom_js
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: bottom_menus
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: bottom_scripts
2016-06-16T06:44:55+00:00 INFO (6): TURPENTINE: Checking ESI block candidate: core_profiler
```  
  
Aside from that I'm not receiving any errors.

**Comment by iamlolz** [comment]
I forgot to dump my vcl:

```
vcl 4.0;
C{
#include <stdlib.h>
#include <stdio.h>
#include <time.h>
#include <pthread.h>
static pthread_mutex_t lrand_mutex = PTHREAD_MUTEX_INITIALIZER;
void generate_uuid(char* buf) {
pthread_mutex_lock(&lrand_mutex);
long a = lrand48();
long b = lrand48();
long c = lrand48();
long d = lrand48();
pthread_mutex_unlock(&lrand_mutex);
sprintf(buf, "frontend=%08lx%04lx%04lx%04lx%04lx%08lx",
a,
b & 0xffff,
(b & ((long)0x0fff0000) >> 16) | 0x4000,
(c & 0x0fff) | 0x8000,
(c & (long)0xffff0000) >> 16,
d
);
return;
}
}C
import std;
backend default {
.host = "127.0.0.1";
.port = "8080";
.first_byte_timeout = 60s;
.between_bytes_timeout = 60s;
}
backend admin {
.host = "127.0.0.1";
.port = "8080";
.first_byte_timeout = 21600s;
.between_bytes_timeout = 21600s;
}
acl crawler_acl {
"127.0.0.1";
}
acl debug_acl {
}
/* -- REMOVED
sub generate_session {
if (req.url ~ ".*[&?]SID=([^&]+).*") {
set req.http.X-Varnish-Faked-Session = regsub(
req.url, ".*[&?]SID=([^&]+).*", "frontend=\1");
} else {
C{
char uuid_buf [50];
generate_uuid(uuid_buf);
static const struct gethdr_s VGC_HDR_REQ_VARNISH_FAKED_SESSION =
{ HDR_REQ, "\030X-Varnish-Faked-Session:"};
VRT_SetHdr(ctx,
&VGC_HDR_REQ_VARNISH_FAKED_SESSION,
uuid_buf,
vrt_magic_string_end
);
}C
}
if (req.http.Cookie) {
std.collect(req.http.Cookie);
set req.http.Cookie = req.http.X-Varnish-Faked-Session +
"; " + req.http.Cookie;
} else {
set req.http.Cookie = req.http.X-Varnish-Faked-Session;
}
}
sub generate_session_expires {
C{
time_t now = time(NULL);
struct tm now_tm = *gmtime(&now);
now_tm.tm_sec += 86400;
mktime(&now_tm);
char date_buf [50];
strftime(date_buf, sizeof(date_buf)-1, "%a, %d-%b-%Y %H:%M:%S %Z", &now_tm);
static const struct gethdr_s VGC_HDR_RESP_COOKIE_EXPIRES =
{ HDR_RESP, "\031X-Varnish-Cookie-Expires:"};
VRT_SetHdr(ctx,
&VGC_HDR_RESP_COOKIE_EXPIRES,
date_buf,
vrt_magic_string_end
);
}C
}
-- */
sub vcl_recv {
if (req.restarts == 0) {
if (req.http.X-Forwarded-For) {
set req.http.X-Forwarded-For =
req.http.X-Forwarded-For + ", " + client.ip;
} else {
set req.http.X-Forwarded-For = client.ip;
}
}
if (!true || req.http.Authorization ||
req.method !~ "^(GET|HEAD|OPTIONS)$" ||
req.http.Cookie ~ "varnish_bypass=1") {
return (pass);
}
if(false) {
set req.http.X-Varnish-Origin-Url = req.url;
}
set req.url = regsuball(req.url, "(.*)//+(.*)", "\1/\2");
if (req.http.Accept-Encoding) {
if (req.http.Accept-Encoding ~ "gzip") {
set req.http.Accept-Encoding = "gzip";
} else if (req.http.Accept-Encoding ~ "deflate") {
set req.http.Accept-Encoding = "deflate";
} else {
unset req.http.Accept-Encoding;
}
}
if (req.http.User-Agent ~ "iP(?:hone|ad|od)|BlackBerry|Palm|Googlebot-Mobile|Mobile|mobile|mobi|Windows Mobile|Safari Mobile|Android|Opera (?:Mini|Mobi)") {
set req.http.X-Normalized-User-Agent = "mobile";
} else if (req.http.User-Agent ~ "MSIE") {
set req.http.X-Normalized-User-Agent = "msie";
} else if (req.http.User-Agent ~ "Firefox") {
set req.http.X-Normalized-User-Agent = "firefox";
} else if (req.http.User-Agent ~ "Chrome") {
set req.http.X-Normalized-User-Agent = "chrome";
} else if (req.http.User-Agent ~ "Safari") {
set req.http.X-Normalized-User-Agent = "safari";
} else if (req.http.User-Agent ~ "Opera") {
set req.http.X-Normalized-User-Agent = "opera";
} else {
set req.http.X-Normalized-User-Agent = "other";
}
set req.http.Host = "[EXAMPLE]";
if (req.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?") {
set req.http.X-Turpentine-Secret-Handshake = "1";
if (req.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?backend") {
set req.backend_hint = admin;
return (pipe);
}
if (req.http.Cookie ~ "\bcurrency=") {
set req.http.X-Varnish-Currency = regsub(
req.http.Cookie, ".*\bcurrency=([^;]*).*", "\1");
}
if (req.http.Cookie ~ "\bstore=") {
set req.http.X-Varnish-Store = regsub(
req.http.Cookie, ".*\bstore=([^;]*).*", "\1");
}
if (req.url ~ "/turpentine/esi/get(?:Block|FormKey)/") {
set req.http.X-Varnish-Esi-Method = regsub(
req.url, ".*/method/(\w+)/.*", "\1");
set req.http.X-Varnish-Esi-Access = regsub(
req.url, ".*/access/(\w+)/.*", "\1");
if (req.http.X-Varnish-Esi-Method == "esi" && req.esi_level == 0 &&
!(true || client.ip ~ debug_acl)) {
return (synth(403, "External ESI requests are not allowed"));
}
}
if (req.http.Cookie !~ "frontend=" && !req.http.X-Varnish-Esi-Method) {
if (client.ip ~ crawler_acl ||
req.http.User-Agent ~ "^(?:ApacheBench/.*|.*Googlebot.*|JoeDog/.*Siege.*|magespeedtest\.com|Nexcessnet_Turpentine/.*)$") {
set req.http.Cookie = "frontend=crawler-session";
} else {
return (pipe);
}
}
if (true &&
req.url ~ ".*\.(?:css|js|jpe?g|png|gif|ico|swf)(?=\?|&|$)") {
unset req.http.Cookie;
unset req.http.X-Varnish-Faked-Session;
set req.http.X-Varnish-Static = 1;
return (hash);
}
if (req.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?(?:backend|api|isAjax=true|isAjax=true/.*|isAjax=true*|\.user\.ini|ajax/login|ajax/login/.*|ajax/login*|attaches|attaches/.*|awall|awall/.*|backend|backend/.*|cash-back-rewards.html|catalog|catalog/.*|checkout|checkout/.*|checkout*|checkout/cart/add|checkout/cart/add/|checkout/cart/add/.*|checkout/cart/add*|contacts|contacts/.*|contact-us.html|cron\.php|customer|customer/.*|customer*|dailyexport-wg909gah09g0\.csv|dbinterface|dbinterface/.*|downloader|downloader/.*|ebizautoresponder|ebizautoresponder/.*|ebizmarts_abandonedcart|ebizmarts_abandonedcart/.*|ewayadmin|ewayadmin/.*|ewayrapid|ewayrapid/.*|feedback.html|feedback.html/.*|giftcards|giftcards/.*|GuestToReg|GuestToReg/.*|hammer-club.html|hammer-club.html/.*|index.php|index.php/.*|index.php*|index\.php|index\.php/.*|index\.php*|index\.php/backend|index\.php/backend/.*|insurance|insurance/.*|is_valid_email|is_valid_email/.*|is_valid_email*|magenotification|magenotification/.*|magmi|magmi/.*|media/dailyexport-wg909gah09g0\.csv|moneybookers|moneybookers/.*|monkey|monkey/.*|onestepcheckout|onestepcheckout/|onestepcheckout/.*|onestepcheckout*|onestepcheckout/ajax/login|onestepcheckout/ajax/login/|onestepcheckout/ajax/login/.*|onestepcheckout/ajax/login*|/onestepcheckout/ajax/login/|onestepcheckoutadmin|onestepcheckoutadmin/.*|onestepcheckoutadmin*|paypal|paypal/.*|popular|popular/.*|ppc|ppc/.*|products-daily\.csv|request-a-quote.html|request-a-quote.html/.*|saveAddressOnestepcheckout|saveAddressOnestepcheckout/.*|saveAddressOnestepcheckout*|save_shipping|save_shipping/.*|save_shipping*|search|search/.*|shipestimation|shipestimation/.*|shipestimation*|sli|sli/.*|stripe|stripe/.*|tools|tools/.*|var|var/.*|webforms|webforms/.*|wishlist|wishlist/.*)" ||
req.url ~ "\?.*__from_store=") {
return (pipe);
}
if (true &&
req.url ~ "(?:[?&](?:__SID|XDEBUG_PROFILE)(?=[&=]|$))") {
return (pass);
}
if (req.url ~ "[?&](utm_source|utm_medium|utm_campaign|gclid|cx|ie|cof|siteurl)=") {
set req.url = regsuball(req.url, "(?:(\?)?|&)(?:utm_source|utm_medium|utm_campaign|gclid|cx|ie|cof|siteurl)=[^&]+", "\1");
set req.url = regsuball(req.url, "(?:(\?)&|\?$)", "\1");
}
if (true && req.url ~ "[?&](utm_source|utm_medium|utm_campaign|utm_content|utm_term|gclid|cx|ie|cof|siteurl)=") {
set req.url = regsuball(req.url, "(?:(\?)?|&)(?:utm_source|utm_medium|utm_campaign|utm_content|utm_term|gclid|cx|ie|cof|siteurl)=[^&]+", "\1");
set req.url = regsuball(req.url, "(?:(\?)&|\?$)", "\1");
}
if(false) {
set req.http.X-Varnish-Cache-Url = req.url;
set req.url = req.http.X-Varnish-Origin-Url;
unset req.http.X-Varnish-Origin-Url;
}
return (hash);
}
}
sub vcl_pipe {
unset bereq.http.X-Turpentine-Secret-Handshake;
set bereq.http.Connection = "close";
}
sub vcl_hash {
if (true && req.http.X-Varnish-Static) {
hash_data(req.url);
if (req.http.Accept-Encoding) {
hash_data(req.http.Accept-Encoding);
}
return (lookup);
}
if(false && req.http.X-Varnish-Cache-Url) {
hash_data(req.http.X-Varnish-Cache-Url);
} else {
hash_data(req.url);
}
if (req.http.Host) {
hash_data(req.http.Host);
} else {
hash_data(server.ip);
}
hash_data(req.http.Ssl-Offloaded);
if (req.http.X-Normalized-User-Agent) {
hash_data(req.http.X-Normalized-User-Agent);
}
if (req.http.Accept-Encoding) {
hash_data(req.http.Accept-Encoding);
}
if (req.http.X-Varnish-Store || req.http.X-Varnish-Currency) {
hash_data("s=" + req.http.X-Varnish-Store + "&c=" + req.http.X-Varnish-Currency);
}
if (req.http.X-Varnish-Esi-Access == "private" &&
req.http.Cookie ~ "frontend=") {
hash_data(regsub(req.http.Cookie, "^.*?frontend=([^;]*);*.*$", "\1"));
}
return (lookup);
}
sub vcl_hit {
}
sub vcl_backend_response {
set beresp.grace = 30s;
set beresp.http.X-Varnish-Host = bereq.http.host;
set beresp.http.X-Varnish-URL = bereq.url;
if (bereq.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?") {
unset beresp.http.Vary;
set beresp.do_gzip = true;
if (beresp.status != 200 && beresp.status != 404) {
set beresp.ttl = 30s;
set beresp.uncacheable = true;
return (deliver);
} else {
if (beresp.http.Set-Cookie) {
set beresp.http.X-Varnish-Set-Cookie = beresp.http.Set-Cookie;
unset beresp.http.Set-Cookie;
}
unset beresp.http.Cache-Control;
unset beresp.http.Expires;
unset beresp.http.Pragma;
unset beresp.http.Cache;
unset beresp.http.Age;
if (beresp.http.X-Turpentine-Esi == "1") {
set beresp.do_esi = true;
}
if (beresp.http.X-Turpentine-Cache == "0") {
set beresp.ttl = 30s;
set beresp.uncacheable = true;
return (deliver);
} else {
if (true &&
bereq.url ~ ".*\.(?:css|js|jpe?g|png|gif|ico|swf)(?=\?|&|$)") {
set beresp.ttl = 1209600s;
set beresp.http.Cache-Control = "max-age=1209600";
} elseif (bereq.http.X-Varnish-Esi-Method) {
if (bereq.http.X-Varnish-Esi-Access == "private" &&
bereq.http.Cookie ~ "frontend=") {
set beresp.http.X-Varnish-Session = regsub(bereq.http.Cookie,
"^.*?frontend=([^;]*);*.*$", "\1");
}
if (bereq.http.X-Varnish-Esi-Method == "ajax" &&
bereq.http.X-Varnish-Esi-Access == "public") {
set beresp.http.Cache-Control = "max-age=" + regsub(
bereq.url, ".*/ttl/(\d+)/.*", "\1");
}
set beresp.ttl = std.duration(
regsub(
bereq.url, ".*/ttl/(\d+)/.*", "\1s"),
300s);
if (beresp.ttl == 0s) {
set beresp.ttl = 30s;
set beresp.uncacheable = true;
return (deliver);
}
} else {
if (bereq.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?about-us\.html") { set beresp.ttl = 1209600s; } else if (bereq.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?blog") { set beresp.ttl = 1209600s; } else if (bereq.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?blog/.*") { set beresp.ttl = 1209600s; } else if (bereq.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?brand-assets\.html") { set beresp.ttl = 1209600s; } else if (bereq.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?freight-charges\.html") { set beresp.ttl = 1209600s; } else if (bereq.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?hammer-club\.html") { set beresp.ttl = 1209600s; } else if (bereq.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?in-store-pickup\.html") { set beresp.ttl = 1209600s; } else if (bereq.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?request-a-quote\.html") { set beresp.ttl = 1209600s; } else if (bereq.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?returns-policy.html") { set beresp.ttl = 1209600s; } else if (bereq.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?sitemap.xml") { set beresp.ttl = 86400s; } else if (bereq.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?store-locations.html") { set beresp.ttl = 1209600s; } else if (bereq.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?testimonial/") { set beresp.ttl = 1209600s; } else if (bereq.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?testimonial/.*") { set beresp.ttl = 1209600s; } else if (bereq.url ~ "^(/media/|/skin/|/js/|/)(?:(?:index|litespeed)\.php/)?warranty-claims\.html") { set beresp.ttl = 1209600s; } else { set beresp.ttl = 1209600s; }
}
}
}
return (deliver);
}
}
sub vcl_deliver {
if (req.http.X-Varnish-Faked-Session) {
set resp.http.Set-Cookie = req.http.X-Varnish-Faked-Session +
"; expires=" + resp.http.X-Varnish-Cookie-Expires + "; path=/";
if (req.http.Host) {
if (req.http.User-Agent ~ "^(?:ApacheBench/.*|.*Googlebot.*|JoeDog/.*Siege.*|magespeedtest\.com|Nexcessnet_Turpentine/.*)$") {
set resp.http.Set-Cookie = resp.http.Set-Cookie +
"; domain=" + regsub(req.http.Host, ":\d+$", "");
} else {
if (req.http.Host ~ "" && "" ~ "..") {
set resp.http.Set-Cookie = resp.http.Set-Cookie +
"; domain=";
} else {
set resp.http.Set-Cookie = resp.http.Set-Cookie +
"; domain=" + regsub(req.http.Host, ":\d+$", "");
}
}
}
set resp.http.Set-Cookie = resp.http.Set-Cookie + "; httponly";
unset resp.http.X-Varnish-Cookie-Expires;
}
if (req.http.X-Varnish-Esi-Method == "ajax" && req.http.X-Varnish-Esi-Access == "private") {
set resp.http.Cache-Control = "no-cache";
}
if (true || client.ip ~ debug_acl) {
set resp.http.X-Varnish-Hits = obj.hits;
set resp.http.X-Varnish-Esi-Method = req.http.X-Varnish-Esi-Method;
set resp.http.X-Varnish-Esi-Access = req.http.X-Varnish-Esi-Access;
set resp.http.X-Varnish-Currency = req.http.X-Varnish-Currency;
set resp.http.X-Varnish-Store = req.http.X-Varnish-Store;
} else {
unset resp.http.X-Varnish;
unset resp.http.Via;
unset resp.http.X-Powered-By;
unset resp.http.Server;
unset resp.http.X-Turpentine-Cache;
unset resp.http.X-Turpentine-Esi;
unset resp.http.X-Turpentine-Flush-Events;
unset resp.http.X-Turpentine-Block;
unset resp.http.X-Varnish-Session;
unset resp.http.X-Varnish-Host;
unset resp.http.X-Varnish-URL;
unset resp.http.X-Varnish-Set-Cookie;
}
}
```

**Comment by aricwatson** [comment]
Just to be sure - have you tested w/the Varnish bypass cookie?

Can you compare the items that are posted to ajax script with and without the bypass cookie to see if there's anything missing when Varnish is present?

**Comment by iamlolz** [comment]
HI @aricwatson, thank you for getting back to me.

It doesn't work with or without the bypass cookie, however it does work if I bypass varnish altogether by using port 8080. I had varnish setup before I implemented Turpentine and it worked(though doesn't do much without turpentine).

**Comment by iamlolz** [comment]
I've noticed that with varnish/turpentine it doesn't appear to be setting the persistent_shopping_cart cookie correctly.(with or without the cookie bypass)  
  
**POST: Request with Varnish/Turpentine:**  
```
X-Varnish-Set-Cookie:frontend=pur7g9qrain60tqiu8i0md0nm4; expires=Tue, 21-Jun-2016 00:59:55 GMT; path=/; domain=52.73.143.44; httponly
```  
  
**GET: Reload checkout page with Varnish/Turpentine:**  
```
Set-Cookie:frontend=pur7g9qrain60tqiu8i0md0nm4; expires=Tue, 21-Jun-2016 00:59:56 GMT; path=/; domain=52.73.143.44; httponly
```  
  
**POST Request without Varnish/Turpentine(port :8080):**  
```
Set-Cookie:frontend=p68gae453c815k3afd5jp5d6e2; expires=Tue, 21-Jun-2016 00:57:36 GMT; path=/; domain=52.73.143.44; httponly
Set-Cookie:frontend=deleted; expires=Thu, 01-Jan-1970 00:00:01 GMT; path=/; domain=52.73.143.44; httponly
Set-Cookie:frontend=g65tfkdj52v7hacurp370dqhu6; expires=Tue, 21-Jun-2016 00:57:36 GMT; path=/; domain=52.73.143.44; HttpOnly
Set-Cookie:customer_group=1; expires=Tue, 20-Jun-2017 00:57:36 GMT; path=/; domain=52.73.143.44; httponly
Set-Cookie:persistent_shopping_cart=w5dqccfXqZIHls13JCsaWWpNK3xcOr6xtxMiELGYFqDhUsHDs1; expires=Tue, 20-Jun-2017 00:57:36 GMT; path=/; domain=52.73.143.44; httponly
```  
  
**GET: Reload checkout page without Varnish/Turpentine(port :8080):**  
```
Set-Cookie:frontend=g65tfkdj52v7hacurp370dqhu6; expires=Tue, 21-Jun-2016 00:57:37 GMT; path=/; domain=52.73.143.44; httponly
Set-Cookie:persistent_shopping_cart=w5dqccfXqZIHls13JCsaWWpNK3xcOr6xtxMiELGYFqDhUsHDs1; expires=Tue, 20-Jun-2017 00:57:37 GMT; path=/; domain=52.73.143.44; httponly
```

**Comment by aricwatson** [comment]
I notice on your POST request that two different frontend cookies are send, and one set to 'deleted' - that's with the varnish bypass on so unrelated to Varnish/Turpentine. I'd suggest debugging this.

**Comment by iamlolz** [comment]
I'm not saying that it's not related in some way, but that POST request is the one that works, correctly logging in and not emptying the cart.

**Comment by aricwatson** [comment]
Ah I see. So, it looks like without Varnish/Turpentine, the ajax one step checkout sets the frontend cookie, then deletes it, then sets a new cookie, along with customer_group.

It's not doing that under Varnish/Turpentine.

> It sends a POST request to /onestepcheckout/ajax/login/ and I have this blacklisted, as well as all of the checkout pages. Here are the headers for that request:

I'm not sure this is working - can you double-check that? Your response headers look like it's still getting processed by Varnish.

**Comment by iamlolz** [comment]
Sorry about the miscommunication @aricwatson. Trying to find that sweet spot between brevity and enough details.

That's what I was thinking when I saw the headers. When I go to the checkout page(/onestepcheckout/index/) it has no varnish headers at all, like it shouldn't. But the ajax POST request(/onestepcheckout/ajax/login/) has varnish headers which seems odd.

**So the timeline is:**  
- /onestepcheckout/index/ - GET request. No varnish headers.
- /onestepcheckout/ajax/login/ - POST request. **Has varnish headers.**
- /onestepcheckout/index/ - GET request. No varnish headers. 302 redirect as cookies aren't present.
- /checkout/cart/ - GET request. No varnish headers. Shows this page with "shopping cart is empty" error.

Here is my over-the-top list of blacklisted urls for the checkout:
```
onestepcheckout
onestepcheckout/
onestepcheckout/.*
onestepcheckout*
onestepcheckout/ajax
onestepcheckout/ajax/
onestepcheckout/ajax/.*
onestepcheckout/ajax*
onestepcheckout/ajax/login
onestepcheckout/ajax/login/
onestepcheckout/ajax/login/.*
onestepcheckout/ajax/login*
onestepcheckout/index
onestepcheckout/index/
onestepcheckout/index/.*
onestepcheckout/index*
```

**Comment by aricwatson** [comment]
> /onestepcheckout/ajax/login/ - POST request. Has varnish headers.

Hmm I'm running out of ideas. That is quite a large URL blacklist - it might be worth testing with just the onestepcheckout in case there's some sort of length limit on the blacklist regex, or an error somewhere in there that means it's not all getting processed?

**Comment by iamlolz** [comment]
Hi @aricwatson. I gave it a go and removed all of them but onestepcheckout but to no avail. Are POST requests piped/passed by default? Should they even need to be blacklisted?

**Comment by gewaechshaus** [comment]
We got some similar setups, just blacklisted
onestepcheckout/ seems to work fine in our case...

**Comment by crasx** [comment]
You just helped me solve an issue I had. My issue was if users created an account during checkout they would be sent to the cart page instead of the success page. I traced it down to the same issue of the frontend cookie not be deleted and reset

In my case I was checking for certain urls (checkout) and passing them if they matched. To fix the issue I had to pipe them. More specifically my url check happened **before**:
```
if (!true || //req.http.Authorization ||
req.method !~ "^(GET|HEAD|OPTIONS)$" ||
req.http.Cookie ~ "varnish_bypass=1") {
return (pipe);
}
```

If you look at the same if statement in your vcl you will see that you are returning pass instead of pipe. If you return pass the vcl_deliver overrides the cookie headers returned by the server

**Comment by iamlolz** [comment]
@gewaechshaus Thanks for letting me know. I'll double check over my blacklist and make sure there isn't something else that could be cancelling it out.

@crasx I changed it from pipe to pass to help with some slow POST requests I was having, from issue [#1129](https://github.com/nexcess/magento-turpentine/issues/1129). I reverted the change back to pipe and issue unfortunately remains.

It's very curious that you were having the same problem with cookies and being redirected to the cart page, maybe this isn't the exact code responsible but maybe it is a pipe/pass issue. Thank for letting me know what you found, hopefully it's pointed me in the right direction. This one has me scratching my head.

**Comment by mdlonline** [comment]
@iamlolz Where in the VCL did you add the pipe/pass part?

**Comment by iamlolz** [comment]
@mdlonline Sorry for the delay mate. Line 100 of my pasted VCL.

```
if (!true || req.http.Authorization ||
req.method !~ "^(GET|HEAD|OPTIONS)$" ||
req.http.Cookie ~ "varnish_bypass=1") {
return (pass);
}
```

**Comment by aricwatson** [comment]
@iamlolz A couple thoughts/ideas

> @crasx I changed it from pipe to pass to help with some slow POST requests I was having, from issue #1129. I reverted the change back to pipe and issue unfortunately remains.

From the varnish docs, it seems like it *should* work with `pipe` - the difference is that with pass the rest of the VCL gets processed, whereas with pipe Varnish gets totally out of the way (see [here](http://book.varnish-software.com/4.0/chapters/VCL_Built_in_Subroutines.html#vcl-vcl-recv)) - perhaps debug this a little more? You could even do a special check to match the onestepcheckout on req.url and only `pipe` in that case, and use pass for the other requests...

I'd consider dropping some `std.log` statements into the VCL to try to detect if you're getting to that `return (pipe)` call on those ajax requests. The std.log should show up with varnishlog.

**Comment by ToonSpinISAAC** [comment]
HI @iamlolz, have you found a solution for your problem yet?

**Comment by iamlolz** [comment]
@ToonSpinISAAC Unfortunately I never did, it was wasting so much of my time that I ended up just removing varnish/turpentine. A real shame because it was the only problem I had left to solve.

**Comment by pieterjanliekens** [comment]
I've got the same issue.

**Comment by pieterjanliekens** [comment]
Too bad... I believe this might be related to ESI blocks, policy.
