### ISSUE TITLE
Cart empty when adding the first product

### ISSUE THREAD

**Issue by zlep** [nexcess/magento-turpentine#1367]
Hi, if I add a product to my cart it stays empty. I already checked the closed issues and this seems a common issue but mine seems a little bit different. Because if I add another product it works. So basically: The first product does not work, the second works.

Any ideas? Thank you very much.

**Comment by rbrown** [comment]
https://github.com/nexcess/magento-turpentine/wiki/FAQ#im-seeing-an-empty-cart-after-clicking-add-to-cart

What version of turpentine are you using? What version of Varnish are you using. What does your vcl file look like? How do requests get to varnish? It it listening on port 80 and this happens or are you using ssl for your insecure_base_url and have something terminating ssl in front of varnish? If so does  https://github.com/nexcess/magento-turpentine/pull/1360 help?

**Comment by zlep** [comment]
Hi, thanks for your quick reply. I'm using the newest master version of turpentine and nginx. I guess my problem is related to https://github.com/nexcess/magento-turpentine/pull/1360 I'm using https on my base insecure url. Which turpentine version should I use (which includes your fix?) Thank you very much.

Btw. One more question: Can Turpetine + Varnish break a CSS element? Because I'm using the Ultimo theme and my cart icon disappears on all sub pages which is pretty strange. Thanks.

**Comment by miguelbalparda** [comment]
@zlep glad you could find a solution for your problem. 

> Btw. One more question if you don't mind: Can Turpetine + Varnish break a CSS element? Because I'm using the Ultimo theme and my cart icon disappears on all sub pages which is pretty strange. Thanks.
This is not the CSS breaking but a block being cached incorrectly because of your theme architecture. I suggest you to check other issues and the ESI section of the wiki to fully understand why this is happening and how to solve it. Specifically with Ultimo we've seen lots of issues but most of them were resolved.

**Comment by zlep** [comment]
@miguelbalparda Thanks. Yeah, will do. Do you have an idea which issue I could check? I found this one https://github.com/nexcess/magento-turpentine/issues/887 but I'm not sure if it's what I'm looking for and where to add the <disableEsiInjection>1</disableEsiInjection> exactly. Would be really nice of you if you could help me a little bit. Thank you very much in advance.

**Comment by miguelbalparda** [comment]
Everything you need is explained [here](https://github.com/nexcess/magento-turpentine/wiki/ESI_Cache_Policy).

**Comment by zlep** [comment]
Great, thanks. If anybody has the same problem. I got it working by adding 

`<disableEsiInjection>1</disableEsiInjection>` to `cart_sidebar` in app/design/frontend/base/default/layout/turpentine_esi.xml 
So, still not 100% sure if this is the correct place, because I always thought, you should not edit base files, though?
