### ISSUE TITLE
ESI_Cache_Policy for prices and add to cart button?

### ISSUE THREAD

**Issue by zlep** [nexcess/magento-turpentine#1398]
Hi,

I'm checking if customers are logged in with "`<?php if(Mage::getSingleton('customer/session')->isLoggedIn()): ?>`" for the **price** and the **add to cart button** in price.phtml, list.phtml and addtocart.phtml

It worked without varnish but with varnish I guess it caches these views so that even if the customer is logged in, it doesn't show the price and the add to cart button. Furthermore I have prices per customer so I guess I have to exclude prices from caching.

Could I achieve this by adding a ESI_Cache_Policy with <access>private</access> ? If yes, could anybody please tell me, which the corresponding blocks are? Or is there a better way?

Thank you very much in advance

**Comment by miguelbalparda** [comment]
This seems to be a duplicated for the most part of https://github.com/nexcess/magento-turpentine/issues/964

**Comment by zlep** [comment]
Ok, I changed 

>     if (req.http.X-Varnish-Esi-Access == "customer_group" &&
>             req.http.Cookie ~ "customer_group=") {
>         hash_data(regsub(req.http.Cookie, "^.*?customer_group=([^;]*);*.*$", "\1"));
>     }

to

>  if (req.http.Cookie ~ "customer_group=") {
>         hash_data(regsub(req.http.Cookie, "^.*?customer_group=([^;]*);*.*$", "\1"));
>     }

in my default.vcl and hit Apply Varnish config in system -> cache management.

But either it is not working or I did it wrong.

**Comment by miguelbalparda** [comment]
While the issue is duplicated, that might not be the right solution for you. In that issue there are quite a few other issues mentioned, my sugesstion would be to check them all and also read the documentation. Please keep in mind this is not a plug and play extensions, some changes might be required to make it work in your store.

**Comment by zlep** [comment]
Hm, there's no other confirmed working solution in this reference. That's why I asked if it wouldn't be easier to just set the corresponding blocks to private (someone mentioned it in another closed issue). My problem is, I don't know how these blocks are called and I'm not sure how I could figure it out.

**Comment by miguelbalparda** [comment]
That is the best recipe for breaking things 😄 From what you said, I think you should contact a developer with some frontend experience. Also the [Wiki](https://github.com/nexcess/magento-turpentine/wiki/) is always a good resource to understand some concepts of this module and [caching](https://github.com/nexcess/magento-turpentine/wiki/ESI_Cache_Policy) in general.

**Comment by zlep** [comment]
Not very helpful, to be honest. I thought somebody could at least give me some hints what I'm doing wrong. It obviously worked for some others with similar issues.

**Comment by miguelbalparda** [comment]
Have you read the entire Wiki? The documentation on customer_groups is quite clear in there plus there are a few open and closed tickets with a lot of useful info. Also there are plenty of tickets on how to avoid certain blocks from being cached from an XML and even how to do the same check in the frontend with JS if you don't want to use the features we provide.

**Comment by mabigo** [comment]
price blocks are anonymous. you will never be able to define esi policy over them. No one ever succeeded on this, as far i can remember. You still may develop a custom ajax-based solution

**Comment by zlep** [comment]
Yes, I read the entire Wiki. I'm not an expert but I'm trying to learn. Everybody has to start at the beginning, hasn't it? I also read a lot of issues but it's not so easy to connect them to the own problem. 

To be honest (I know this sounds stupid), I have 2 problems:

1.) I'm not sure if the default.vcl is the correct place to make the above mentioned changes. Or do I have to edit another file?

2.) If this entire solution is not working for me, I'd like to try the private block solution. You said I could mess things up if I don't know what to do. Still, I'd like to try it. That's the only way I can learn things, can't I? :) My problem still is, I don't know how to figure out how these blocks are called. Maybe you could give me a hint or at least link to a reference where this is explained?

**Comment by miguelbalparda** [comment]
This will depend on your theme, that is what "this is not a plug and play extension" means. 
What you want to learn is the relation between block names, XML files and phtml files and it's mostly explained [here](http://devdocs.magento.com/guides/m1x/magefordev/mage-for-dev-4.html). If you already know this you should be cool and if you don't, hiring someone might be the best option.

The VCL file is a generated file, which means you can write on it but it will be replaced with the new generated file next time you save from the admin. To avoid this, you can use custom includes which are also documented in the wiki.

**Comment by zlep** [comment]
Yes, but @mabigo said, price blocks are always anonymous so I guess I can forget my initial idea with the private blocks? Or can I put the prices in a custom block and make this block private? I'm not looking for a plug and play solution. I'm looking for tips from experts which way I should follow up. If I know the way to go, I will figure out how to achieve it. But I did not get one single good tip here, unfortunately. You still closed it with a reference to a solution you're not sure is working, though.

Btw. Just hiring someone and giving up without trying to solve it by yourself is never a good option.

**Comment by miguelbalparda** [comment]
The way to go is explained in the Wiki with lots of practical examples in the open and closed issues. Issues similar to yours have been solved quite a few times already and with all the info in those issues you should be able to figure out everything you need to solve this. You will need to fully understand a lot of concepts to fix this from Magento frontend XML/Blocks to cache policies, going trough Varnish and ESI policies and I tried to point you in the right direction but this might take you some time to assimilate, there are a lot of concepts involved and while it can be frustrating, the module is pretty easy to use once you understand the basics explained in the links I sent you, specifically the use of [customer_group](https://github.com/nexcess/magento-turpentine/wiki/ESI_Cache_Policy).

**Comment by miguelbalparda** [comment]
Just realized something about your 2 comment. You made a change to the default.vcl file which was overwritten the second when you clicked Apply. If you want to try this again, you can do the same change in the template we use to generate the file.

**Comment by zlep** [comment]
Yes, that's what I thought I'm doing wrong.  And it is not explained in the Wiki ;)

So I have to make the changes in  app/ code/community/Nexcessnet/Turpentine/misc/version-4.vcl ? And then hit the Apply button to make my changes work? This procedure is really not explained in the Wiki, I swear :D

**Comment by miguelbalparda** [comment]
You can edit the version-4.vcl file, but your change will be overwritten if you ever update the module. It is pretty clear once you understand the module and see the PHP classes that this entire module is only a wrapper to generate and apply a VCL so you don't have to do it manually and that we use templates for the VCL generation. Also the process to include custom code is actually documented [here](https://github.com/nexcess/magento-turpentine/wiki/Configuration#servers) under Custom VCL File Location.

**Comment by zlep** [comment]
Ok, I got it working now. The problem is, my issue IS NOT a duplicate of https://github.com/nexcess/magento-turpentine/issues/964

I don't need to cache entire pages per **customer group**.
I need to cache entire pages per **customer**

So, I think my issue is still valid and should not be closed, isn't it? Or do you have a quick idea for this?

**Comment by miguelbalparda** [comment]
That is what private should do. From the wiki
private        : one version per client is stored in cache

**Comment by zlep** [comment]
> price blocks are anonymous. you will never be able to define esi policy over them. 

So?
