### ISSUE TITLE
Search box is cached in Magento 1.9.2.2 with sample pack

### ISSUE THREAD

**Issue by ADDISON74** [nexcess/magento-turpentine#938]
My test version is as follows:
- Apache 2.2. PHP 5.5, MySQL 5.6, Varnish 3
- Magento 1.9.2.1
- Magento Sample 1.9.1.0
- Turpentine - dev branch
- No changes in settings or other extensions.

1) Clear your browser cache and reload your website.
2) In search box enter a word and click on Search button. See the word you searched in inside text box.
3) Click any link inside the page to visit a new page. Look again to search box. The word you searched before is still inside the box. Some other pages will have it too there, but others not.
4) If you visit again those pages with that word inside the search box, you will find it there.

This is a very basic issue I know you fixed long time ago.

**Comment by ADDISON74** [comment]
please check this behavior live here: http://94.176.2.184/

**Comment by aricwatson** [comment]
OK, this seems to be working so far in my testing. Try changing your ESI policies for the header block to add a flush event for *controller_action_layout_render_before_catalogsearch_result_index*

```
        <reference name="header">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <wishlist_item_save_after/>
                        <wishlist_item_delete_after/>
                        <sales_quote_save_after/>
                        <controller_action_layout_render_before_catalogsearch_result_index>
                    </flush_events>
                </params>
            </action>
        </reference>
```

I'll test some more, but so far this seems to fix the problem.

**Comment by ADDISON74** [comment]
So far so good. Your solution seems to fix the issue completely. Let's test it more and do not forget to include this fix inside dev branch if everything is OK.

PS - Hope you'll find a way to fix for "___SID=U issue" and an elegant way to "fix urls for Compare side block - Clear All and Individual Clear". At that moment Turpentine could be used in my production environment. :)

**Comment by ADDISON74** [comment]
I am getting an warning in Magento system.log file: 

"Warning: simplexml_load_string(): Entity: line 48: parser error : Opening and ending tag mismatch: controller_action_layout_render_before_catalogsearch_result_index line 47"

Is your xml tag missing <strong>/</strong> character at the end of tag?

controller_action_layout_render_before_catalogsearch_result_index<strong>/</strong>

**Comment by aricwatson** [comment]
Nice catch - should be this:

```
        <reference name="header">
            <action method="setEsiOptions">
                <params>
                    <access>private</access>
                    <flush_events>
                        <wishlist_item_save_after/>
                        <wishlist_item_delete_after/>
                        <sales_quote_save_after/>
                        <controller_action_layout_render_before_catalogsearch_result_index />
                    </flush_events>
                </params>
            </action>
        </reference>
```

Notice the slash that was missing in ` <controller_action_layout_render_before_catalogsearch_result_index />` - sorry!

**Comment by aricwatson** [comment]
This fix has been committed to the default turpentine_esi.xml

**Comment by ADDISON74** [comment]
Let's re-open this issue. 

Please clear your Magento cache, sessions, cookies and restart Varnish. Go to your website, visit a category and do a search for any word. If you leave this search result page going back to category the search box will be empty. But if you go to home page, search word fills the search box! This is the issue I want to report. I really don't understand why in all pages search box will be empty, but not for home page.

**Comment by ADDISON74** [comment]
I installed a few moments ago in a subdirectory a new Magento the same like the one in root, but without installing Turpentine extension. This version from subdirectory is working with Varnish configuration too. The mentioned issue is not appearing with this version, which is the same like the one in root. Search box is empty after leaving the search result page.

**Comment by ADDISON74** [comment]
I did more testing. We still have an issue. Search box content is cached when using navigation links (categories) in Magento default theme (RWD). For all the other links like products, home page, cms pages, search box is empty. Sometimes only home page keeps the search box word, but for categories its content is empty. It could be other event for being flushed in header.

All caches in Cache Management are disable except those two from Turpentine.

Please re-open this issue and let's continue testing.

**Comment by ADDISON74** [comment]
Here are more details about 2 different testings. Clear Magento cache and session folders, clear you browser cache and cookies, restart varnish service.

<strong>SCENARIO 1</strong>: 

1) Enter the search word "soap" in your home page and click on Search button. You will get this page for search results.

![start-11](https://cloud.githubusercontent.com/assets/8360474/11586984/36696068-9a7f-11e5-915d-2399d60117fc.jpg)

2) Click on page logo for going to Home page. You can see word soap is still in input search box (value="soap" in Developer Tools).

![start-12](https://cloud.githubusercontent.com/assets/8360474/11587030/6b62c278-9a7f-11e5-8135-1d31f07a1d5e.jpg)

3) Click on category link Women. You can see word "soap" is not in input search box (value="" in Developer Tools. If you click on any other category link you will get the same result. Even visiting other pages like product page input search box will have no value.

![start-13](https://cloud.githubusercontent.com/assets/8360474/11587093/c4efac5c-9a7f-11e5-9c96-f9d4c4cd7161.jpg)

**Comment by ADDISON74** [comment]
Clear again Magento cache and session folders, clear you browser cache and cookies, restart varnish service.

<strong>SCENARIO 2: STARTING FROM A CATEGORY</strong>: 

1) Click on category link Women and enter the search word "soap" then click on Search button. You will get the page for search results, now click again on category link Women. You can see word "soap" is still in input search box (value="soap" in Developer Tools).

![start-21](https://cloud.githubusercontent.com/assets/8360474/11587158/2f436e0e-9a80-11e5-975a-1f0cc645bced.jpg)

2) Click on category link Men. You can see word "soap" is still in input search box (value="soap" in Developer Tools). If you click on any other category link you will get the same result.

![start-22](https://cloud.githubusercontent.com/assets/8360474/11587366/8296fa2a-9a81-11e5-8fee-3a1474ea8826.jpg)

3) Click on page logo for going back to Home page. You can see word "soap" is not in input search box (value="" in Developer Tools). Even visiting other pages like product page or cms pages, input search box will have no value.

![start-23](https://cloud.githubusercontent.com/assets/8360474/11587229/9fe4137a-9a80-11e5-9fbe-db9e7e5c0950.jpg)

**Comment by ADDISON74** [comment]
Please RE-OPEN this issue. Thank you.

**Comment by ADDISON74** [comment]
I tried this code in local.xml but still the same issue as mentioned in my images:

    <reference name="header">
        <action method="setEsiOptions">
            <params>
                <disableEsiInjection>1</disableEsiInjection>
            </params>
        </action>
    </reference>

**Comment by ADDISON74** [comment]
Let's dig this more in detail. I searched for dispatch events related to catalogsearch. This a Magento CE 1.9.2.2. Here is the list I found:

- catalogsearch_reset_search_result
- catalogsearch_searchable_attributes_load_after
- catalogsearch_index_process_start
- catalogsearch_index_process_complete

None of these worked if they are added as flush_events in turpentine header.

**Comment by ADDISON74** [comment]
These two events are in function <strong>rebuildIndex</strong> (Regenerate all Stores index).
File: app/code/core/Mage/CatalogSearch/Model/Fulltext.php (lines 79 and 86)
- catalogsearch_index_process_start
- catalogsearch_index_process_complete

This event is in function <strong>resetSearchResults</strong> (Reset search results).
File: app/code/core/Mage/CatalogSearch/Model/Resource/Fulltext.php (line 305)
- catalogsearch_reset_search_result

This event is in function <strong>_getSearchableAttributes</strong> (Retrieve searchable attributes).
File: File: app/code/core/Mage/CatalogSearch/Model/Resource/Fulltext.php (line 431)
- catalogsearch_searchable_attributes_load_after

I will use this event for flushing search box and see what is happening:
<strong>controller_action_layout_render_before_catalogsearch_reset_search_result</strong>.

**Comment by ADDISON74** [comment]
It seems to work as expected for the mentioned event. Please do your test too. Pay attention to Block HTML Output being disabled in Cache Management. If this block is enabled in my case famous "___SID issue" appears very quick. When this issue appears the URLs containing it will cache the search box (only for all category links in top navigation and footer links).

**Comment by aricwatson** [comment]
I was just able to get around to testing this change (adding a flush event for `controller_action_layout_render_before_catalogsearch_reset_search_result`) and unfortunately it doesn't seem to be working. This doesn't appear to be an event that Magento actually dispatches (at least in CE). 

I also tested `catalogsearch_reset_search_result` and that doesn't work either. I notice in the log that the event isn't getting detected and used to flush the header block. I tested a few more as well.

I think the problem here is the sequence of events:

1) (on homepage) - enter search term and hit enter
2) as search results page is loaded, the header block cache is cleared due to the flush event `controller_action_layout_render_before_catalogsearch_result_index`
3) display search results page - and Varnish stores the header block (which includes the search query)
4) click on homepage - homepage loads, and the header block is loaded from varnish using the value stored in #3 above... 


Theoretically, you could resolve this by setting a flush event to trigger on step 4 (when the homepage is loaded) - however in practice this would mean clearing the header block cache on pretty much any page load - which obviously isn't useful!

I don't think it's useful to spend time to come up with a fix for this specific scenario, given that I'm sure other themes will approach this differently. I'd suggest for problems like these using client-side javascript similr to that suggested in https://github.com/nexcess/magento-turpentine/pull/521 - or just alter the template for the block with the search form to not show the search query at all.

**Comment by ADDISON74** [comment]
For the moment I am flashing the event I mentioned before. It is working by now:
controller_action_layout_render_before_catalogsearch_reset_search_result

**Comment by ricsipontaz** [comment]
Is there a solution for this issue?

**Comment by miguelbalparda** [comment]
There is a solution in this very same post.

**Comment by ricsipontaz** [comment]
Which one? I've tried  controller_action_layout_render_before_catalogsearch_reset_search_result. But it doesn't work.

**Comment by mikeshield13** [comment]
How did you solve this?

**Comment by mikeshield13** [comment]
I've just found a weird thing. It works If I logged in, but it doesn't for guests. How is it possible? @miguelbalparda @ADDISON74 @ricsipontaz @aricwatson

**Comment by mikeshield13** [comment]
Unfortunately it doesn't work, just the log in action flushes the cache and it works on the first try only...
Can somebody re-open this ticket? Or show me a solution?
